### ISSUE TITLE
Clickable room names in tournament overview

### ISSUE THREAD

**Issue by nickkolok** [IPTnet/ipt_connect#265]
![изображение](https://user-images.githubusercontent.com/5008131/94342041-fd119300-0016-11eb-8a15-2fcca4146c88.png)

Add an optional `link` field to the Room admin page. If the filed is blank, the Room name is not clickable (just as it is now). Otherwise it is an anchor for the link.

This will be useful for online tournaments, where a Room name is often exactly the link to join, especially if Matches will be implemented (see #146). Moreover, for offline tournaments the link can lead to a tutorial on how to find the Room :-)

Developing the idea, we can have Room details pages with all the necessary info (probably with markdown support, see #199). However, that should can be disabled somehow.

**Comment by CptOrange16** [comment]
Hi, i would like to work on this issue

**Comment by nickkolok** [comment]
Hi! Thank you for your interest in `ipt_connect`. You are welcome!
I advice you to start with reading our Contributor's guide: https://github.com/IPTnet/ipt_connect/blob/dev/CONTRIBUTING.md

**Comment by CptOrange16** [comment]
@nickkolok i've been following the guide and I just installed all the requirements and ran the server using: 

     python manage.py runserver. 
Seems to run great. 
When I run the tests i get the following error:  

    django.db.utils.OperationalError: no such table: IPTdev_participant

Do i need to run some other commands to set things up? Or is this one of those known bugs you mention in the guide?

<details>
<summary>Click for full error description</summary>

```Creating test database for alias 'default'...
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/home/sara/personal/Hacktoberfest/IPT connect/test_env2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/sara/personal/Hacktoberfest/IPT connect/test_env2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sara/personal/Hacktoberfest/IPT connect/test_env2/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/sara/personal/Hacktoberfest/IPT connect/test_env2/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/sara/personal/Hacktoberfest/IPT connect/test_env2/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/sara/personal/Hacktoberfest/IPT connect/test_env2/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/sara/personal/Hacktoberfest/IPT connect/test_env2/local/lib/python2.7/site-packages/django/test/runner.py", line 601, in run_tests
    old_config = self.setup_databases()
  File "/home/sara/personal/Hacktoberfest/IPT connect/test_env2/local/lib/python2.7/site-packages/django/test/runner.py", line 546, in setup_databases
    self.parallel, **kwargs
  File "/home/sara/personal/Hacktoberfest/IPT connect/test_env2/local/lib/python2.7/site-packages/django/test/utils.py", line 187, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/home/sara/personal/Hacktoberfest/IPT connect/test_env2/local/lib/python2.7/site-packages/django/db/backends/base/creation.py", line 77, in create_test_db
    self.connection._test_serialized_contents = self.serialize_db_to_string()
  File "/home/sara/personal/Hacktoberfest/IPT connect/test_env2/local/lib/python2.7/site-packages/django/db/backends/base/creation.py", line 121, in serialize_db_to_string
    serializers.serialize("json", get_objects(), indent=None, stream=out)
  File "/home/sara/personal/Hacktoberfest/IPT connect/test_env2/local/lib/python2.7/site-packages/django/core/serializers/__init__.py", line 129, in serialize
    s.serialize(queryset, **options)
  File "/home/sara/personal/Hacktoberfest/IPT connect/test_env2/local/lib/python2.7/site-packages/django/core/serializers/base.py", line 80, in serialize
    for count, obj in enumerate(queryset, start=1):
  File "/home/sara/personal/Hacktoberfest/IPT connect/test_env2/local/lib/python2.7/site-packages/django/db/backends/base/creation.py", line 117, in get_objects
    for obj in queryset.iterator():
  File "/home/sara/personal/Hacktoberfest/IPT connect/test_env2/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/home/sara/personal/Hacktoberfest/IPT connect/test_env2/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
django.db.utils.OperationalError: no such table: IPTdev_participant```
</details>

**Comment by nickkolok** [comment]
@CptOrange16, it look like our problem. Could you please run the following before running the tests?
```bash
python manage.py makemigrations IPTdev
python manage.py makemigrations IPTdev_pf2
```
This should be runned once; after that, the migrations (which are not committed into the git repo - because they are auto-generated files) should be present, and the tests should run - i.e. they should give another error.

Please reply here about the result :)

**Comment by CptOrange16** [comment]
@nickkolok I've run the migrations. 
Now when i run the tests some of them fail. I do see errors caused by loginas.
Let me know if this is the expected output so I can start making some changes.
<details>
<summary>Click for full error description</summary>

Creating test database for alias 'default'...
System check identified no issues (0 silenced).
......FF......Not in cache: view_cache_tournament_overview_/_anonymous
EEEEEEEEEEEE.....
======================================================================
ERROR: test_as_anonymous_user (loginas.tests.tests.ViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sara/personal/Hacktoberfest/IPT connect/ipt_connect/ipt_connect/loginas/tests/tests.py", line 69, in setUp
    assert django_settings.CSRF_COOKIE_NAME in self.client.cookies
AssertionError

======================================================================
ERROR: test_as_non_superuser (loginas.tests.tests.ViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sara/personal/Hacktoberfest/IPT connect/ipt_connect/ipt_connect/loginas/tests/tests.py", line 69, in setUp
    assert django_settings.CSRF_COOKIE_NAME in self.client.cookies
AssertionError

======================================================================
ERROR: test_as_superuser (loginas.tests.tests.ViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sara/personal/Hacktoberfest/IPT connect/ipt_connect/ipt_connect/loginas/tests/tests.py", line 69, in setUp
    assert django_settings.CSRF_COOKIE_NAME in self.client.cookies
AssertionError

======================================================================
ERROR: test_custom_permissions (loginas.tests.tests.ViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sara/personal/Hacktoberfest/IPT connect/ipt_connect/ipt_connect/loginas/tests/tests.py", line 69, in setUp
    assert django_settings.CSRF_COOKIE_NAME in self.client.cookies
AssertionError

======================================================================
ERROR: test_custom_permissions_as_string (loginas.tests.tests.ViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sara/personal/Hacktoberfest/IPT connect/ipt_connect/ipt_connect/loginas/tests/tests.py", line 69, in setUp
    assert django_settings.CSRF_COOKIE_NAME in self.client.cookies
AssertionError

======================================================================
ERROR: test_custom_permissions_invalid_path (loginas.tests.tests.ViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sara/personal/Hacktoberfest/IPT connect/ipt_connect/ipt_connect/loginas/tests/tests.py", line 69, in setUp
    assert django_settings.CSRF_COOKIE_NAME in self.client.cookies
AssertionError

======================================================================
ERROR: test_get_405_method_not_allowed (loginas.tests.tests.ViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sara/personal/Hacktoberfest/IPT connect/ipt_connect/ipt_connect/loginas/tests/tests.py", line 69, in setUp
    assert django_settings.CSRF_COOKIE_NAME in self.client.cookies
AssertionError

======================================================================
ERROR: test_last_login_not_updated (loginas.tests.tests.ViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sara/personal/Hacktoberfest/IPT connect/ipt_connect/ipt_connect/loginas/tests/tests.py", line 69, in setUp
    assert django_settings.CSRF_COOKIE_NAME in self.client.cookies
AssertionError

======================================================================
ERROR: test_last_login_updated (loginas.tests.tests.ViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sara/personal/Hacktoberfest/IPT connect/ipt_connect/ipt_connect/loginas/tests/tests.py", line 69, in setUp
    assert django_settings.CSRF_COOKIE_NAME in self.client.cookies
AssertionError

======================================================================
ERROR: test_loginas_redirect_url (loginas.tests.tests.ViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sara/personal/Hacktoberfest/IPT connect/ipt_connect/ipt_connect/loginas/tests/tests.py", line 69, in setUp
    assert django_settings.CSRF_COOKIE_NAME in self.client.cookies
AssertionError

======================================================================
ERROR: test_missing_csrf_token_403_forbidden (loginas.tests.tests.ViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sara/personal/Hacktoberfest/IPT connect/ipt_connect/ipt_connect/loginas/tests/tests.py", line 69, in setUp
    assert django_settings.CSRF_COOKIE_NAME in self.client.cookies
AssertionError

======================================================================
ERROR: test_restore_original_user (loginas.tests.tests.ViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sara/personal/Hacktoberfest/IPT connect/ipt_connect/ipt_connect/loginas/tests/tests.py", line 69, in setUp
    assert django_settings.CSRF_COOKIE_NAME in self.client.cookies
AssertionError

======================================================================
FAIL: test_switch_login (grappelli.tests.test_switch.SwitchTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sara/personal/Hacktoberfest/IPT connect/ipt_connect/ipt_connect/grappelli/tests/test_switch.py", line 62, in test_switch_login
    self.assertEqual(t, t_cmp)
AssertionError: '' != '<li><a href="/grappelli/switch/user/3/?redirect=/admin/grappelli/category/" class="grp-switch-user-is-target">Editor001</a></li><li><a href="/grappelli/switch/user/4/?redirect=/admin/grappelli/category/" class="grp-switch-user-is-target">Editor002</a></li>'

======================================================================
FAIL: test_switch_superuser001_editor001 (grappelli.tests.test_switch.SwitchTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sara/personal/Hacktoberfest/IPT connect/ipt_connect/ipt_connect/grappelli/tests/test_switch.py", line 126, in test_switch_superuser001_editor001
    self.assertEqual(t, t_cmp)
AssertionError: '' != '<li><a href="/grappelli/switch/user/1/?redirect=/admin/grappelli/category/" class="grp-switch-user-is-original">Superuser001</a></li><li><a href="/grappelli/switch/user/3/?redirect=/admin/grappelli/category/" class="grp-switch-user-is-target">Editor001</a></li><li><a href="/grappelli/switch/user/4/?redirect=/admin/grappelli/category/" class="grp-switch-user-is-target">Editor002</a></li>'

----------------------------------------------------------------------
Ran 31 tests in 1.782s

FAILED (failures=2, errors=12)
Destroying test database for alias 'default'...

</details>

**Comment by nickkolok** [comment]
@CptOrange16, looks good!

Good luck in making changes. Don't forget to make a dump before and after :)

**Comment by CptOrange16** [comment]
@nickkolok i've cloned a fresh repository (just to rule out any problems cause by my changes) and did all the process and ran the migrations.
Now I am not able to open the server. I can run the runserver file and no errors are shown but nothing loads.
I cannot build with docker compose either:
![imagem](https://user-images.githubusercontent.com/4366792/94861822-04c6a280-0430-11eb-8301-ef3e4c2d99a8.png)

**Comment by nickkolok** [comment]
@CptOrange16, I'm very sorry, but I cannot help you with Docker. I'm not experienced with the technology at all.

Could you please give me the output of `python manage.py runserver`? What do you mean by "nothing loads"?

**Comment by CptOrange16** [comment]
@nickkolok no worries, it was a problem on my machine. It's running ok now.
I made the room name clickable. Currently is hardcoded: if link is true, then show room name with anchor to link, if not show room name without link.
![imagem](https://user-images.githubusercontent.com/4366792/94877352-2c2e6700-0452-11eb-8b75-2ba412555eee.png)

Can you clarify what you mean by:
> Add an optional link field to the Room admin page. If the filed is blank, the Room name is not clickable (just as it is now). Otherwise it is an anchor for the link.

Do i need to add a link field to the room table? Something like :
Room Name (clickable, goes to link)     | Room Link | Round 1 | Round 2 ...
Room Name (not clickable, just name) |                   | Round 1 | Round 2 ...

**Comment by nickkolok** [comment]
@CptOrange16 
> Do i need to add a link field to the room table?

No, it's enough that the Room name is clickable. I meant just that the site admin should have an ability to specify the link to the room. E.g. "Euler" room can lead to the host university site with a map, or just to https://en.wikipedia.org/wiki/Leonhard_Euler

In the Room admin page (smth like http://127.0.0.1:8000/admin/IPTev/room/5/change/) the should be not only the name of the Room, but also the link to it.

Also it would be great if you push your code into a temporary branch and share it with us!

**Comment by CptOrange16** [comment]
@nickkolok ok, i'll start working on it.
I am working on a branch in my forked repository, do i have do make a pull request for you do be able to see it?

**Comment by nickkolok** [comment]
@CptOrange16 , no pull request is needed. You are working in your local repo, aren't you? Thus, you can just push to a temporary branch, and it will be shown here: https://github.com/CptOrange16/ipt_connect/branches

**Comment by CptOrange16** [comment]
@nickkolok yes I forgot to push my branch to remote.
I think i'm getting very close to the goal, but i'm having problems getting the link to work.
I create a room with link and name in the admin panel:
![imagem](https://user-images.githubusercontent.com/4366792/94980449-c9a49c00-0521-11eb-8caa-376aebb83e69.png)
But in the room panel (in normal page) the link does not show. I think there is something missing that is not allowing the link to be saved to the db or maybe i'm not acessing it the right way.

Here is the branch: https://github.com/CptOrange16/ipt_connect/tree/clickable_room_names_in_tournament_overview_265

**Comment by nickkolok** [comment]
Have you pressed the "Save" button?

Have you made and run the migrations? It looks like you should do so, because you are changing the structure of the database:
```bash
python manage.py makemigrations
python manage.py migrate
```

What happens if you save a room with a link, then navigate to the rooms list in admin panel and open the same room? Is the link still here?

**Comment by CptOrange16** [comment]
Yes, after changing the database structure I ran all those commands for the migrations.
On the admin page after i add the room i click save and things work as expected. When i go to the room table i see the room name and also the rounds (if i create rounds for the room). The only think i cannot see is the link. So I think I might be saving the link wrong.
After I got back to the admin panel, the link and the name are there.

**Comment by nickkolok** [comment]
I've commented your commits. Some remarks are already outdated, because I reviewed you commits one-by-one.
So, the main point is: what is the type of `thisroom.0.0`? It may be even a Round object! Then, the `Room` may be `thisroom.0.0.room`, and the link may be `thisroom.0.0.room.get_link`

**Comment by CptOrange16** [comment]
@nickkolok hello, you were right. I was investigating the orderedroundsperroom and yes the thisroom is in fact a round.
I created a dictionary in the views.py that contains not only the round list but also the room name and link. 
I think everything is working properly, let me know if there is something missing

Also, tests and dead links are ok. But there is a difference in a single line in one of the dump files

**Comment by nickkolok** [comment]
Thank you! The code looks good, however I haven't tested it yet.

Could you please check if your patch also fixes #188 and #156 ?

**Comment by CptOrange16** [comment]
It seems to fix both #188 and #156 
![imagem](https://user-images.githubusercontent.com/4366792/95027891-e2cd5a00-0693-11eb-9425-81dfc3c790ff.png)

**Comment by nickkolok** [comment]
I've run the code. It works pretty good, but there are some issues.

1. Internet is not only working by HTTPS. Moreover, it is not a good idea to prefix a link with `https://` even if it has no  protocol specified: some links van start with `//` or be relative (the latter is not very probable). Thus, we should leave the protocol up to the site administrator.

2. Could you please mention the issues being closed, in the commit message? `... close #265, close #188, close #156`

**Comment by nickkolok** [comment]
If you wish to continue contributing, you may be interested in:
#175 
#173
#131
#275
(from the most simple to the most interesting)

However, I may be wrong, so don't hesitate to work on whatever you want :)

**Comment by nickkolok** [comment]
@CptOrange16 , do you need any help?)

**Comment by CptOrange16** [comment]
@nickkolok hello, sorry had a busy week at work and didn't have a chance to check github.

Just to recap, you want me to:
1. remove that https part of the links
2. mention in that commit the issue that I'm fixing

**Comment by nickkolok** [comment]
@CptOrange16 Yes. Could you please mention all the issues being fixed?

**Comment by nickkolok** [comment]
@CptOrange16 Any progress on this?)
