### ISSUE TITLE
Correct phrase about updates in overview

### ISSUE THREAD

**Issue by nickkolok** [IPTnet/ipt_connect#97]
@vbonvin wrote:
>Since we are now using the update_all function to update the score, this message is not really correct anymore. I'd replace with something like
>"The results are updated once after each round - you will be notified via email once the update has been made"

1. Do we really send emails after **each** update of scores?

2.
> we are now using the update_all function to update the score

What does "now" mean? As I understand, recalculating of scores after every round saving had been done before I touched the code, hadn't it?

**Comment by vbonvin** [comment]
> Do we really send emails after each update of scores?

That's four emails in total (5 in case of semifinals). I said after each "rounds" but it's rather after each "fights". Last edition in which I was active (2017), the participants were hungry for the score updates - I was working in the hotel lobby and some of them came to ask when the scores would be online :)

> What does "now" mean? As I understand, recalculating of scores after every round saving had been done before I touched the code, hadn't it?

Yes. By "now", I mean in the second version of the code with the improvements brought by @xuod in 2017. Not that recent, I confess. Initially, the scores were updated each time new data was entered in the admin panel but it ended up in terrible lags on server side due to the heavy computation requested. That's why we opted for an update_all function triggered only once after each qualifying PF.

**Comment by nickkolok** [comment]
> That's four emails in total (5 in case of semifinals).

Are the e-mails sent automatically by ipt_connect?

> the scores were updated each time new data was entered in the admin panel but it ended up in terrible lags on server side due to the heavy computation requested

I believe that the reason for lags is not the "terrible" computations. For now (AFAIK that wasn't me who did so), saving a round triggers update for all teams involved and for the problem presented. AFAIK,  the computations were nit the main reason for lag - the transactions was. I've made an attempt to group the transactions into atomic ones.
Are 3-4 seconds after saving a round a terrible lag?

**Comment by vbonvin** [comment]
> Are the e-mails sent automatically by ipt_connect?

No

> I believe that the reason for lags is not the "terrible" computations.

You believe wrong, then. I developed the first version, so I know at least some of its flaws.

The current version is much more robust in that regard, but when you want to update the scores of 18 teams at the end of the fourth rounds it takes some time, period. Good for us if you find a way to reduce that to a few seconds, but that's probably still too much to trigger the computations automatically when someone wants to access a page on the server that is not cached (which was the original behaviour before the version we have now).

**Comment by nickkolok** [comment]
> but that's probably still too much to trigger the computations automatically when someone wants to access a page on the server
Surely. So, the most "heavy" data are cached in such fields as `total_points`, aren't they?
